name: make test build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: get packer sum
      run: |
        curl https://github.com/hashicorp/packer/raw/master/go.sum -o /tmp/go.sum
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('/tmp/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: version
      run: |
        VERSION_FILE=pwnagotchi/__init__.py
        PWN_VERSION=v$(cat $VERSION_FILE | grep version | cut -d"'" -f2)-$(echo $GITHUB_SHA | head -c7)
        echo "::set-env name=PWN_VERSION::${PWN_VERSION}"
    - name: make
      run: |
        export TERM=linux
        sudo apt-get update
        sudo apt-get install qemu-system-arm qemu-user-static bmap-tools kpartx
        sudo make clean
        sudo -E env "PATH=$PATH" make install
        sudo make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=${PWN_VERSION}
