name: make

on:
  push:
    branches:
    - test_img

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        export TERM=linux
        sudo apt-get update
        sudo apt-get install kpartx qemu-user-static
        make all
    - name: Commit files
      shell: bash
      run: |
        git add pwnagotchi-raspbian-lite-*.zip
        git diff-index --quiet HEAD \
        || git -c user.name="GitHub" -c user.email="noreply@github.com" commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m "Test build ${{ github.head_ref }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build
