name: make

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        export TERM=linux
        sudo apt-get update
        sudo apt-get install qemu-user qemu --fix-missing
        make all
