name: Make test build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get packer sum
      run: |
        curl https://github.com/hashicorp/packer/raw/master/go.sum -o go.sum
    - name: Init go cache
      id: go-cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Init packer-builder cache
      id: builder-cache
      uses: actions/cache@v1
      with:
        path: /tmp/packer-builder-arm-image
        key: cache-${{ runner.os }}-packer-builder-arm-image-${{ github.sha }}
        restore-keys: cache-${{ runner.os }}-packer-builder-arm-image-
    - name: Get version
      run: |
        VERSION_FILE=pwnagotchi/__init__.py
        PWN_VERSION=v$(cat $VERSION_FILE | grep version | cut -d"'" -f2)-$(echo $GITHUB_SHA | head -c7)
        echo "::set-env name=PWN_VERSION::${PWN_VERSION}"
    - name: Install required packages
      run: |
        export TERM=linux
        sudo apt-get update
        sudo apt-get install kpartx qemu-user-static
    - name: Make image for ${{ env.PWN_VERSION }}
      run: |
        sudo -E env "PATH=$PATH" make install
        #sudo make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=${PWN_VERSION}
    - name: Set cache permissions
      run: |
        sudo chmod -R 777 /tmp/packer-builder-arm-image
        sudo chmod -R 777 ~/go/pkg/mod
