name: make

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get install qemu --fix-missing
        make all
