name: make test build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        export TERM=linux
        sudo apt-get update
        sudo apt-get install kpartx qemu-user-static
        sudo make clean
        sudo -E env "PATH=$PATH" make install
        sudo make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=$(echo $GITHUB_SHA | head -c7)
